spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sentstorm_db
    username: admin
    password: sdbpass
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  docker:
    compose:
      enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/sentstorm

  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      media-output-path: ./uploads
      
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: encpass
    key-store-type: PKCS12
    key-alias: sentstorm